TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Egobude.Products': TRUE
    modules:
      egobudeProducts:
        label: 'My Project Back End Management'
        controller: '\Egobude\Products\Controller\StandardController'
        description: 'Contains multiple modules related to management of My Project'
        icon: 'icon-briefcase'
        resource: 'TYPO3_Neos_Backend_Module_Management'
  TYPO3CR:
    contentDimensions:
      'language':
        # The default dimension that is applied when creating nodes without specifying a dimension
        default: 'de'
        # The default preset to use if no URI segment was given when resolving languages in the router
        defaultPreset: 'de'
        label: 'Language'
        icon: 'icon-language'
        presets:
          'en':
            label: 'English'
            values: ['en']
            uriSegment: 'en'
            constraints:
              system:
                'typo3': false
          'de':
            label: 'Deutsch'
            values: ['de']
            uriSegment: 'de'
      'system':
        # The default dimension that is applied when creating nodes without specifying a dimension
        default: 'neos'
        # The default preset to use if no URI segment was given when resolving languages in the router
        defaultPreset: 'neos'
        label: 'System'
        icon: 'icon-book'
        presets:
          'neos':
            label: 'Neos'
            values: ['neos']
            uriSegment: 'neos'
          'typo3':
            label: 'TYPO3'
            values: ['typo3']
            uriSegment: 'typo3'